Repository RavenProject/Ravencoin, pull requests merged in 2021-04, with the labels that each got.

#936 Cleanups: remove unused and old files (PR #936).
  .github/old-workflows/build-arm32v7-disable_wallet.yml
  .github/old-workflows/build-arm32v7.yml
  .github/old-workflows/build-linux64-disable_wallet.yml
  .github/old-workflows/build-linux64.yml
  .github/old-workflows/build-osx.yml
  .github/scripts/01-update-docker.sh
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
  contrib/gitian-keys/README.md
  contrib/gitian-keys/achow101-key.pgp
  contrib/gitian-keys/aschildbach-key.pgp
  contrib/gitian-keys/bluematt-key.pgp
  contrib/gitian-keys/btcdrak-key.pgp
  contrib/gitian-keys/cdecker-key.pgp
  contrib/gitian-keys/centaur1-key.pgp
  contrib/gitian-keys/cfields-key.pgp
  contrib/gitian-keys/devrandom-key.pgp
  contrib/gitian-keys/erkmos.pgp
  contrib/gitian-keys/fanquake-key.pgp
  contrib/gitian-keys/gavinandresen-key.pgp
  contrib/gitian-keys/jl2012-key.pgp
  contrib/gitian-keys/jonasschnelli-key.pgp
  contrib/gitian-keys/jtimon-key.pgp
  contrib/gitian-keys/laanwj-key.pgp
  contrib/gitian-keys/luke-jr-key.pgp
  contrib/gitian-keys/marcofalke-key.pgp
  contrib/gitian-keys/meshcollider-key.pgp
  contrib/gitian-keys/michagogo-key.pgp
  contrib/gitian-keys/petertodd-key.pgp
  contrib/gitian-keys/prab-key.pgp
  contrib/gitian-keys/sipa-key.pgp
  contrib/gitian-keys/tcatm-key.pgp
  contrib/gitian-keys/wtogami-key.pgp
  contrib/raven-qt.pro
Labels: cleanup code

#937 Cleanups: move files from root to better locations (PR #937)
  contrib/Dockerfile
  contrib/Dockerfile.amd64
  contrib/Dockerfile.arm32v7
  contrib/static-builds/README.md
  contrib/static-builds/script.sh
  contrib/static-builds/staticbuild.md
  doc/release_checklist.md
  run.sh
Labels: cleanup code

#938 GUI: Add preview to QR code drag and drop (PR #938)
  src/qt/receiverequestdialog.cpp
Labels: enhancement, gui

#941 Update Documentation
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#944 Cleanups: Move urls to defines.
  src/qt/guiconstants.h
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
Labels: cleanup code, gui

#934 Contrib: Copy install_db4.sh from bitcoin (PR #934).
  contrib/install_db4.sh
Labels: enhancement

#939 Redesigned the mnemonic dialog GUI for wallet creation into 3 less co…
  src/Makefile.qt.include
  src/qt/forms/mnemonicdialog.ui
  src/qt/forms/mnemonicdialog1.ui
  src/qt/forms/mnemonicdialog2.ui
  src/qt/forms/mnemonicdialog3.ui
  src/qt/mnemonicdialog.cpp
  src/qt/mnemonicdialog.h
Labels: enhancement, gui

#955 Build: Add aarch64-linux-gnu
  .github/scripts/00-install-deps.sh
  .github/scripts/02-copy-build-dependencies.sh
  .github/scripts/03-export-path.sh
  .github/scripts/04-configure-build.sh
  .github/scripts/05-binary-checks.sh
  .github/scripts/06-package.sh
  .github/workflows/build-raven.yml
  depends/packages/packages.mk
  depends/packages/qt.mk
Labels: enhancement

#945 Build: Switch to building on ubuntu 18.04 bionic
  .github/scripts/00-install-deps.sh
  .github/workflows/build-raven.yml
Labels: build oddities, enhancement

#935 Doc: Add build-ubuntu.md (PR #935)
  doc/build-ubuntu.md
Labels: documentation

#956 GUI: Adjust blue and orange to match the logo.
  src/qt/guiconstants.h
Labels: enhancement, gui

#959 Doc: General updates to multiple files.
  CONTRIBUTING.md
  README.md
  doc/README.md
  doc/benchmarking.md
  doc/bips.md
  doc/developer-notes.md
  doc/fuzzing.md
  doc/gitian-building.md
  doc/reduce-memory.md
  doc/release-notes-pr12924.md
  doc/release-process.md
  doc/translation_process.md
  doc/travis-ci.md
Labels: documentation, enhancement

#960 Cleanups: Remove unused scripts.
  contrib/gitian-build.sh
  contrib/verify-commits/README.md
  contrib/verify-commits/allow-revsig-commits
  contrib/verify-commits/gpg.sh
  contrib/verify-commits/pre-push-hook.sh
  contrib/verify-commits/trusted-git-root
  contrib/verify-commits/trusted-keys
  contrib/verify-commits/trusted-sha512-root-commit
  contrib/verify-commits/verify-commits.sh
Labels: cleanup code

#873 Feature: Add P2SH support - Core Protocol Development Proposal 001 (PR #873)
  .github/ISSUE_TEMPLATE.md
  src/Makefile.test.include
  src/assets/assets.cpp
  src/assets/assets.h
  src/assets/messages.cpp
  src/bloom.cpp
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/core_write.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/rpc/blockchain.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/script/interpreter.cpp
  src/script/ismine.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/sign.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/test/assets/asset_p2sh_tests.cpp
  src/test/multisig_tests.cpp
  src/test/script_standard_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  src/versionbits.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/feature_assets_p2sh.py
  test/functional/test_runner.py
Labels: consensus, requested feature

#962 Build: Use package-version from raven-config.h when naming files (PR #962)
  .github/scripts/06-package.sh
Labels: build oddities, enhancement
