Repository RavenProject/Ravencoin, pull requests merged in 2021-09, with the labels that each got.

#1069 [GUI] Fixed display for atomic swap transactions in wallet
  src/Makefile.qt.include
  src/qt/raven.qrc
  src/qt/res/icons/tx_atomic_swap.png
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
Labels: enhancement, gui, asset related

#1075 gui: set window minimum size to usable default
  src/qt/forms/overviewpage.ui
  src/qt/forms/reissueassetdialog.ui
  src/qt/raven.cpp
Labels: gui

#1085 Bip39: Add support multilanguage
  src/qt/forms/mnemonicdialog2.ui
  src/qt/forms/mnemonicdialog3.ui
  src/qt/mnemonicdialog.cpp
  src/qt/mnemonicdialog.h
  src/wallet/bip39.cpp
  src/wallet/bip39.h
  src/wallet/bip39_chinese_simplified.h
  src/wallet/bip39_chinese_traditional.h
  src/wallet/bip39_english.h
  src/wallet/bip39_french.h
  src/wallet/bip39_italian.h
  src/wallet/bip39_japanese.h
  src/wallet/bip39_korean.h
  src/wallet/bip39_spanish.h
  test/functional/test_framework/wallet_util.py
  test/functional/test_runner.py
  test/functional/wallet_bip44_multilanguage.py
Labels: enhancement, gui
