Repository RavenProject/Ravencoin, pull requests merged in 2021-05, with the labels that each got.

#972 Depends: Update boost download url (PR #972)
  depends/packages/boost.mk
Labels: build related

#964 Update to build-ubuntu.md (PR #964)
  doc/build-ubuntu.md
Labels: build related, documentation

#967 Doc: Replaced bitcoin-core with Ravencoin in Github template (PR #967)
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#971 GUI: Send RVN, Transfer Assets. We don't pay (PR #971)
  src/qt/forms/sendassetsentry.ui
  src/qt/forms/sendcoinsentry.ui
Labels: enhancement, gui

#1000 fix: broken links due to search and replace (PR #1000).
  src/qt/paymentrequest.proto
  src/qt/ravenunits.h
  src/rpc/mining.cpp
Labels: documentation, enhancement

#999 build: fix includes for freebsd (PR #999).
  src/crypto/ethash/lib/ethash/endianness.hpp
  src/crypto/ethash/lib/keccak/keccak.c
Labels: build related

#978 GUI: Warning when opening IPFS-urls. (PR #978)
  src/qt/overviewpage.cpp
Labels: gui, security related

#976 GUI: Add Wallet -> Get my words (PR #976)
  src/qt/ravengui.cpp
  src/qt/ravengui.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: enhancement, gui

#1003 doc: add build-freebsd.md and updates to build-unix.md
  doc/build-freebsd.md
  doc/build-unix.md
Labels: documentation

#1007 build: Suppress -Wdeprecated-copy warnings
  configure.ac
Labels: build related, enhancement

#1008 qt, refactor: remove build warnings Qt 5.15.x
  src/qt/addresstablemodel.cpp
  src/qt/assetsdialog.cpp
  src/qt/bantablemodel.cpp
  src/qt/createassetdialog.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/optionsmodel.cpp
  src/qt/overviewpage.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/raven.cpp
  src/qt/ravenamountfield.cpp
  src/qt/ravengui.h
  src/qt/receiverequestdialog.cpp
  src/qt/reissueassetdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/qt/sendcoinsdialog.cpp
  src/qt/splashscreen.cpp
  src/qt/splashscreen.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactionview.cpp
  src/qt/utilitydialog.h
Labels: build related, cleanup code, gui

#1024 refactor: remove unneccesary parantheses.
  src/txdb.cpp
Labels: build related

#1027 testnet updated seeds
  src/chainparamsseeds.h
Labels: enhancement

#1028 verification.cpp update variables to be const
  src/validation.cpp
Labels: cleanup code, security related

#1026 contrib: Dockerfile updated
  contrib/Dockerfile
  contrib/Dockerfile.amd64
  contrib/Dockerfile.arm32v7
Labels: build related, enhancement

#1033 build: update Expat 2.4.1 change source to github.
  depends/packages/expat.mk
  doc/dependencies.md
Labels: build related

#1030 gui: option to hide text in toolbar
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/raven.qrc
  src/qt/ravengui.cpp
  src/qt/ravengui.h
  src/qt/res/icons/rvntext.png
Labels: gui, requested feature

#1032 depends: libevent update (btc#21991)
  depends/packages/libevent.mk
  depends/patches/libevent/0001-fix-windows-getaddrinfo.patch
  doc/dependencies.md
Labels: build related, upstream fix

#1034 gui: add version to modal overlay
  src/qt/forms/modaloverlay.ui
  src/qt/modaloverlay.cpp
Labels: enhancement, gui

#1036 Drop buggy TableViewLastColumnResizingFixer class (btc#204)
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/receivecoinsdialog.cpp
  src/qt/receivecoinsdialog.h
  src/qt/transactionview.cpp
  src/qt/transactionview.h
Labels: bug, gui

#1038 Move app out of if, and remove qt version checks
  src/qt/raven.cpp
Labels: cleanup code

#1039 fix typo
  src/qt/restrictedfreezeaddress.cpp
Labels: gui

#1040 gui: toolbar move code to match order in toolbar
  src/qt/ravengui.cpp
Labels: cleanup code, gui

#1042 p2p: add fixed seeds if less than 5 addresses available after 60 sec.
  src/net.cpp
Labels: enhancement

#1043 translation: update transifex client config.
  .tx/config
Labels: translation
