Repository RavenProject/Ravencoin, pull requests merged in 2021-06, with the labels that each got.

#1019 consensus: correct verification of transactions pre p2sh-asset activation
  src/consensus/tx_verify.cpp
  src/script/script.cpp
  src/script/script.h
Labels: bug, consensus

#1025 gui: osx darkmode
  share/qt/Info.plist.in
Labels: gui

#1048 Fix handling of nonstandard txns and "-acceptnonstdtxn"
  src/init.cpp
Labels: enhancement, upstream fix

#1050 GUI: Reissue asset spinboxes. Disable if unit is max.
  src/qt/reissueassetdialog.cpp
Labels: enhancement, gui

#1060 gui: Manage assets - update list when shown.
  src/qt/reissueassetdialog.cpp
Labels: asset related, gui

#1057 Introduce a Shuffle for FastRandomContext and use it in wallet
  src/random.h
  src/test/random_tests.cpp
  src/wallet/wallet.cpp
Labels: build related, upstream fix

#1063 Release: version 4.7.0test2
  configure.ac
Labels: versioning / release

#1070 net: Do not force dns seeds by default.
  src/net.h
Labels: enhancement

#1068 GUI: Get my words, re-lock wallet if not bip44.
  src/qt/walletmodel.cpp
Labels: bug, gui
