Repository RavenProject/Ravencoin, pull requests merged in 2022-02, with the labels that each got.

#1103 Add asset support for IsFromMe
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: asset related

#1111 Dummy arguments for QApplication
  src/qt/raven.cpp
  src/qt/test/test_main.cpp
Labels: gui, security related

#1122 fix: include array to fix building for osx.
  src/wallet/bip39.cpp
Labels: build related

#1125 gui: Wallet -> Get my words, auto close.
  src/qt/walletview.cpp
Labels: enhancement, gui

#1126 backport: Shut down if trying to connect a corrupted block
  src/validation.cpp
Labels: enhancement, upstream fix

#1128 GUI: Change non-ideal color for dark mode on "added to transaction" window
  src/qt/assetsdialog.cpp
  src/qt/createassetdialog.cpp
  src/qt/reissueassetdialog.cpp
  src/qt/restrictedassetsdialog.cpp
  src/qt/sendcoinsdialog.cpp
Labels: enhancement, gui

#1132 gui: optional seed extension word rename
  src/qt/forms/mnemonicdialog2.ui
  src/qt/forms/mnemonicdialog3.ui
Labels: gui

#1133 gui: minimum sizes and margins
  src/qt/forms/assetsdialog.ui
  src/qt/forms/createassetdialog.ui
  src/qt/forms/overviewpage.ui
  src/qt/forms/reissueassetdialog.ui
  src/qt/forms/restrictedassetsdialog.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/raven.cpp
Labels: gui

#1134 gui: search for string in whole asset name.
  src/qt/assetfilterproxy.cpp
  src/qt/assetfilterproxy.h
  src/qt/overviewpage.cpp
Labels: gui, asset related

#1138 gui: Create Assets tooltip wording
  src/qt/ravengui.cpp
Labels: gui, asset related

#1145 depends: increase download timeout and retries
  depends/Makefile
Labels: build related

#1159 backport: [validation] Crash if disconnecting a block fails
  src/validation.cpp
Labels: backport

#1160 backport: wallet: Fix Char as Bool in Wallet
  src/wallet/wallet.h
Labels: backport

#1161 backport: gui: Set CConnman byte counters earlier to avoid uninitialized reads
  src/net.cpp
  src/net.h
Labels: backport

#1162 backport: rpc: Fix data race (UB) in InterruptRPC()
  src/rpc/server.cpp
Labels: backport

#1163 backport: fix uninitialized read when stringifying an addrLocal
  src/netaddress.cpp
  src/netaddress.h
Labels: backport

#1164 backport: Introduce a maximum size for locators.
  src/net.h
  src/net_processing.cpp
Labels: backport

#1167 backport: [qt] Fix potential memory leak in newPossibleKey(ChangeCWallet *wallet) (bitcoin #10920)
  src/qt/walletmodeltransaction.cpp
  src/qt/walletmodeltransaction.h
Labels: backport

#1173 backport: Make CWallet::FundTransaction atomic (bitcoin #11864)
  src/wallet/wallet.cpp
Labels: backport

#1180 docs: Update dependencies for Ubuntu 21.10
  doc/build-ubuntu.md
Labels: documentation

#1169 backport: Remove redundant locks (bitcoin #11733)
  src/qt/addresstablemodel.cpp
Labels: backport

#1144 gui: create and reissue asset views - browse ipfs button
  src/qt/createassetdialog.cpp
  src/qt/createassetdialog.h
  src/qt/forms/createassetdialog.ui
  src/qt/forms/reissueassetdialog.ui
  src/qt/reissueassetdialog.cpp
  src/qt/reissueassetdialog.h
Labels: enhancement, gui

#1170 backport: net: Add missing locks in net.{cpp,h} (bitcoin #11744)
  src/net.cpp
  src/net.h
Labels: backport
